name: biashara_smart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  fl_chart: ^1.1.1
  intl: ^0.20.2 # Use 0.19.0 as it is the most stable for current SDKs
  pdf: ^3.11.3
  printing: ^5.14.2
  google_generative_ai: ^0.4.0  # Add this line
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Hakikisha njia hii ni sahihi
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#0F172A" # Rangi ya nyuma (Background)
  adaptive_icon_foreground: "assets/icon.png" # Logo yenyewe